'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{spawnSync}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');const root=path.resolve(__dirname,'..');
const php=(body)=>spawnSync('php',['-r',`require '${root}/Server/php/bootstrap.php';${body}`],{encoding:'utf8'});

test('package and license service persists configurable states, unlimited limits and safe assignment counts',()=>{const result=php(`$c=new Neutral\\Core\\AppConfig(['APP_ENV'=>'test','DB_TYPE'=>'mysql','DB_HOST'=>'x','DB_NAME'=>'x','DB_USER'=>'x'],'${root}');$d=new Neutral\\Core\\Database($c);$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('CREATE TABLE packages(id INTEGER PRIMARY KEY AUTOINCREMENT,package_key TEXT UNIQUE,name TEXT,description TEXT,entitlements_json TEXT,limits_json TEXT,status TEXT);CREATE TABLE licenses(id INTEGER PRIMARY KEY AUTOINCREMENT,license_key TEXT UNIQUE,organization_name TEXT,package_id INTEGER,seat_limit INTEGER,device_limit INTEGER,device_limit_mode TEXT,status TEXT);CREATE TABLE license_users(license_id INTEGER,user_id INTEGER,license_role TEXT,membership_status TEXT,device_limit INTEGER,device_limit_mode TEXT,PRIMARY KEY(license_id,user_id));');$r=new ReflectionProperty($d,'pdo');$r->setAccessible(true);$r->setValue($d,$pdo);$s=new Neutral\\Core\\AccountLicenseService($d);$p=$s->savePackage(null,['key'=>'basic-custom','name'=>'Custom','description'=>'Neutral package','status'=>'active','allowedDevices'=>1,'modules'=>['gps'=>'available','reference-notes'=>'locked']]);$l=$s->saveLicense(null,['key'=>'org-a','organizationName'=>'Organization A','packageId'=>$p['id'],'seatLimit'=>50,'allowedDevices'=>null,'status'=>'active']);echo json_encode(compact('p','l'));`);assert.equal(result.status,0,result.stderr);const data=JSON.parse(result.stdout);assert.equal(data.p.allowedDevices,1);assert.equal(data.p.modules.gps,'available');assert.equal(data.p.modules['reference-notes'],'locked');assert.equal(data.l.seatLimit,50);assert.equal(data.l.deviceLimitSource,'package');});

test('birthday accepts real ISO calendar dates only, including leap years and deletion',()=>{const result=php(`$ok=[Neutral\\Core\\AccountLicenseService::normalizeBirthday('2024-02-29'),Neutral\\Core\\AccountLicenseService::normalizeBirthday('')];$bad=0;foreach(['2023-02-29','2024-02-30','31.12.2024','nonsense'] as $v)try{Neutral\\Core\\AccountLicenseService::normalizeBirthday($v);}catch(RuntimeException $e){$bad++;}echo json_encode(compact('ok','bad'));`);assert.equal(result.status,0,result.stderr);assert.deepEqual(JSON.parse(result.stdout),{ok:['2024-02-29',''],bad:4});});

test('admin package/license assets and audit clear contract are wired into the production package',()=>{const packageFile=fs.readFileSync(path.join(root,'Web-App/public/admin/commercial-view.js'),'utf8');const audit=fs.readFileSync(path.join(root,'Web-App/public/admin/audit-view.js'),'utf8');assert.match(packageFile,/Packages \/ Entitlements/);assert.match(packageFile,/Licenses \/ Organizations/);assert.match(audit,/Type DELETE/);const api=fs.readFileSync(path.join(root,'Server/public/api/index.php'),'utf8');assert.match(api,/audit\.clear/);assert.match(api,/audit\.clear\.completed/);assert.match(api,/entriesDeleted/);});
