'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{spawnSync}=require('node:child_process');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const root=path.resolve(__dirname,'..');
const php=(body,env={})=>spawnSync('php',['-r',`require '${root}/Server/php/bootstrap.php';${body}`],{encoding:'utf8',env:{...process.env,...env}});
const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');

test('unreferenced license deletes without touching its package while referenced license is rejected',()=>{
 const result=php(`$c=new Neutral\\Core\\AppConfig(['APP_ENV'=>'test','DB_TYPE'=>'mysql','DB_HOST'=>'x','DB_NAME'=>'x','DB_USER'=>'x'],'${root}');$d=new Neutral\\Core\\Database($c);$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec("CREATE TABLE packages(id INTEGER PRIMARY KEY,package_key TEXT,name TEXT,description TEXT,entitlements_json TEXT,limits_json TEXT,status TEXT);INSERT INTO packages VALUES(1,'free','Free',NULL,'{}','{}','active');CREATE TABLE licenses(id INTEGER PRIMARY KEY,license_key TEXT,organization_name TEXT,package_id INTEGER,seat_limit INTEGER,device_limit INTEGER,device_limit_mode TEXT,status TEXT);INSERT INTO licenses VALUES(1,'empty','Empty',1,1,NULL,'package','active'),(2,'used','Used',1,1,NULL,'package','active');CREATE TABLE license_users(license_id INTEGER,user_id INTEGER,license_role TEXT,membership_status TEXT,device_limit INTEGER,device_limit_mode TEXT);INSERT INTO license_users VALUES(2,7,'member','active',NULL,'default');");$r=new ReflectionProperty($d,'pdo');$r->setAccessible(true);$r->setValue($d,$pdo);$s=new Neutral\\Core\\AccountLicenseService($d);$deleted=$s->deleteLicense(1);$blocked='';try{$s->deleteLicense(2);}catch(RuntimeException $e){$blocked=$e->getMessage();}$counts=['packages'=>(int)$pdo->query('SELECT COUNT(*) FROM packages')->fetchColumn(),'licenses'=>(int)$pdo->query('SELECT COUNT(*) FROM licenses')->fetchColumn(),'links'=>(int)$pdo->query('SELECT COUNT(*) FROM license_users')->fetchColumn()];echo json_encode(compact('deleted','blocked','counts'));`);
 assert.equal(result.status,0,result.stderr);const data=JSON.parse(result.stdout);assert.deepEqual(data.deleted,{id:'1',key:'empty'});assert.match(data.blocked,/assigned users or a manager/);assert.deepEqual(data.counts,{packages:1,licenses:1,links:1});
});

test('license delete UI and route retain confirmation, authorization, CSRF, audit and refresh contracts',()=>{const ui=read('Web-App/public/admin/commercial-view.js');const api=read('Server/public/api/index.php');assert.match(ui,/data-delete-license/);assert.match(ui,/confirmAction\('Delete this unreferenced license/);assert.match(ui,/await this\.init\(this\.container\)/);assert.match(api,/method==='DELETE'\) \{[\s\S]*?require_admin_session_permission_or_fail\(\$identity,\$authManager,'admin\.write',\$headers\)/);assert.match(api,/license\.delete/);assert.match(api,/licenseKey/);assert.match(api,/still referenced\.',409/);});

test('session support metadata is conservative across realistic device fixtures',()=>{const fixtures=[
 ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1','', 'iPad','iPadOS','Safari'],
 ['Mozilla/5.0 (iPad; CPU OS 17_6 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 CriOS/128.0.0.0 Safari/604.1','', 'iPad','iPadOS 17.6','Chrome'],
 ['Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1','', 'iPhone','iOS 16.4','Safari'],
 ['Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 Chrome/128.0 Mobile Safari/537.36','', 'Android phone','Android 14','Chrome'],
 ['Mozilla/5.0 (Linux; Android 13; Tablet) AppleWebKit/537.36 Chrome/128.0 Safari/537.36','', 'Android tablet','Android 13','Chrome'],
 ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/128.0 Safari/537.36','', 'Desktop','Windows','Chrome'],
 ['Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) AppleWebKit/605.1.15 Version/17.0 Safari/605.1.15','', 'Desktop','macOS','Safari'],
 ['Mozilla/5.0 AppleWebKit/537.36','', 'Unknown','Unknown','Browser']];
 const encoded=Buffer.from(JSON.stringify(fixtures)).toString('base64');const result=php(`$fixtures=json_decode(base64_decode('${encoded}'),true);$out=[];foreach($fixtures as $f)$out[]=Neutral\\Core\\Phase4SessionRegistry::supportMetadata($f[0],$f[1]);echo json_encode($out);`);assert.equal(result.status,0,result.stderr);const values=JSON.parse(result.stdout);fixtures.forEach((f,i)=>assert.deepEqual(values[i],{deviceClass:f[2],operatingSystem:f[3],browser:f[4]}));});

test('session UI displays user ID and authoritative full installation ID separately from support metadata',()=>{const ui=read('Web-App/public/admin/index.js');assert.match(ui,/Installation \/ Device ID/);assert.match(ui,/#\$\{session\.userId\}/);assert.match(ui,/<code>\$\{session\.deviceId/);assert.match(ui,/Device class/);assert.match(ui,/Operating system/);assert.doesNotMatch(ui,/<th>Device<\/th>\s*<th>Platform/);});

test('backup path probe accepts protected writable directory and rejects unsafe targets',t=>{const base=fs.mkdtempSync(path.join(os.tmpdir(),'neutral-backup-path-'));t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const project=path.join(base,'project');const external=path.join(base,'external');const publicDir=path.join(project,'Web-App/public');fs.mkdirSync(external,{recursive:true});fs.mkdirSync(publicDir,{recursive:true});const file=path.join(base,'file');fs.writeFileSync(file,'x');const env={PATH_EXTERNAL:external,PATH_PROJECT:project,PATH_PUBLIC:publicDir,PATH_FILE:file};const result=php(`$out=[];$out['ready']=Neutral\\Core\\DatabaseBackupService::testDirectory(getenv('PATH_EXTERNAL'),getenv('PATH_PROJECT'));$out['public']=Neutral\\Core\\DatabaseBackupService::testDirectory(getenv('PATH_PUBLIC'),getenv('PATH_PROJECT'));$out['file']=Neutral\\Core\\DatabaseBackupService::testDirectory(getenv('PATH_FILE'),getenv('PATH_PROJECT'));$out['readonly']=Neutral\\Core\\DatabaseBackupService::testDirectory('/sys',getenv('PATH_PROJECT'));$out['missing']=Neutral\\Core\\DatabaseBackupService::testDirectory(getenv('PATH_EXTERNAL').'/missing',getenv('PATH_PROJECT'));foreach(['/tmp/../etc',"/tmp/bad\\0path",'relative/path'] as $p){try{Neutral\\Core\\DatabaseBackupService::normalizeConfiguredDirectory($p);$out['unsafe'][]=false;}catch(RuntimeException $e){$out['unsafe'][]=true;}}echo json_encode($out);`,env);assert.equal(result.status,0,result.stderr);const data=JSON.parse(result.stdout);assert.equal(data.ready.status,'ready');assert.equal(data.public.status,'public_path');assert.equal(data.file.status,'not_directory');assert.equal(data.readonly.status,'not_writable');assert.equal(data.missing.status,'missing');assert.deepEqual(data.unsafe,[true,true,true]);assert.equal(fs.readdirSync(external).length,0);const missing=path.join(base,'must-not-be-created');const guarded=php(`$c=new Neutral\\Core\\AppConfig(['NEUTRAL_BACKUP_KEY'=>str_repeat('k',32),'DB_TYPE'=>'mysql','DB_HOST'=>'x','DB_NAME'=>'x','DB_USER'=>'x'],'${root}');$d=new Neutral\\Core\\Database($c);$s=new Neutral\\Core\\DatabaseBackupService($d,new Neutral\\Core\\SchemaMigrator($d),$c,getenv('PATH_PROJECT'),static fn(array $tables):array=>[],null,getenv('PATH_MISSING'));try{$s->list();echo 'unexpected';}catch(Neutral\\Core\\BackupRuntimeException $e){echo $e->safeCode();}`,{PATH_PROJECT:project,PATH_MISSING:missing});assert.equal(guarded.stdout,'BACKUP_STORAGE_UNAVAILABLE');assert.equal(fs.existsSync(missing),false);});

test('manual service and automatic runner consume the same persisted backup storage setting without exposing the key',()=>{const service=read('Server/php/src/DatabaseBackupService.php');const runner=read('scripts/run-automatic-backup.php');const api=read('Server/public/api/index.php');const ui=read('Web-App/public/admin/index.js');assert.match(service,/configuredDirectory/);assert.match(runner,/\$options\['backupStoragePath'\]/);assert.match(api,/configured_backup_storage_path\(\$settingsService\)/);assert.match(api,/admin\/backups\/path\/test/);assert.match(ui,/Backup storage path/);assert.match(ui,/>Test path</);assert.match(ui,/>Save</);assert.doesNotMatch(ui,/NEUTRAL_BACKUP_KEY|encryption key.*input/i);assert.doesNotMatch(runner,/backupKey\(\)|getenv\(['"]NEUTRAL_BACKUP_KEY/);});

test('backup storage path persists as ordinary installation settings and changes only future service location',t=>{const base=fs.mkdtempSync(path.join(os.tmpdir(),'neutral-backup-setting-'));t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const one=path.join(base,'one');const two=path.join(base,'two');fs.mkdirSync(one);fs.mkdirSync(two);const result=php(`$store=new Neutral\\Core\\Phase4JsonStore(getenv('CONFIG_ROOT'));$settings=new Neutral\\Core\\Phase4SettingsService($store);$first=$settings->update(['settings'=>['backupStoragePath'=>getenv('PATH_ONE')]]);$second=$settings->update(['settings'=>array_merge($first['settings'],['backupStoragePath'=>getenv('PATH_TWO')])]);echo json_encode([$first['settings']['backupStoragePath'],$settings->getAll()['settings']['backupStoragePath'],$second['settings']['backupStoragePath']]);`,{CONFIG_ROOT:path.join(base,'config'),PATH_ONE:one,PATH_TWO:two});assert.equal(result.status,0,result.stderr);assert.deepEqual(JSON.parse(result.stdout),[one,two,two]);});
