'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const{spawnSync}=require('node:child_process');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const php=body=>spawnSync('php',['-r',`require '${root}/Server/php/bootstrap.php';${body}`],{encoding:'utf8'});

test('profile exposes only an authoritative active organization-membership capability',()=>{const result=php(`$c=new Neutral\\Core\\AppConfig(['DB_TYPE'=>'mysql','DB_HOST'=>'x','DB_NAME'=>'x','DB_USER'=>'x']);$d=new Neutral\\Core\\Database($c);$p=new PDO('sqlite::memory:');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$p->exec("CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT,email TEXT,display_name TEXT);CREATE TABLE user_profiles(user_id INTEGER PRIMARY KEY,public_nickname TEXT,phone TEXT,address TEXT,birthday TEXT,privacy_json TEXT);CREATE TABLE licenses(id INTEGER PRIMARY KEY,status TEXT);CREATE TABLE license_users(license_id INTEGER,user_id INTEGER,membership_status TEXT);INSERT INTO users VALUES(1,'solo',NULL,''),(2,'member',NULL,'');INSERT INTO user_profiles VALUES(1,'','','',NULL,'{}'),(2,'','','',NULL,'{}');INSERT INTO licenses VALUES(7,'active');INSERT INTO license_users VALUES(7,2,'active');");$r=new ReflectionProperty($d,'pdo');$r->setAccessible(true);$r->setValue($d,$p);$s=new Neutral\\Core\\AccountLicenseService($d);echo json_encode([$s->profile(1),$s->profile(2)]);`);assert.equal(result.status,0,result.stderr);const [solo,member]=JSON.parse(result.stdout);assert.equal(solo.organizationSharingAvailable,false);assert.equal(member.organizationSharingAvailable,true);assert.ok(Object.values(solo.privacy).every(v=>v===false));});

test('organization sharing is gated in the optional Profile module before mutation',()=>{const service=read('Server/php/modules/profile/module.php');const api=read('Server/public/api/index.php');const ui=read('Web-App/public/user-app.js');assert.match(service,/membership_status='active'.*l\.status='active'/);assert.ok(service.indexOf('Organization sharing requires')<service.indexOf("UPDATE users SET"));assert.doesNotMatch(api,/account\/profile'/);assert.match(ui,/profile\.organizationSharingAvailable \? `<fieldset><legend>Share with my organization/);assert.match(ui,/state\.accountProfile\?\.organizationSharingAvailable/);});

test('route-derived navigation has one accessible token-based active state across reload and auth changes',()=>{const ui=read('Web-App/public/user-app.js');const css=read('Web-App/public/style.css');assert.match(ui,/applyHashRoute/);assert.match(ui,/hashchange/);assert.match(ui,/settings\/\$\{state\.settingsSection\}/);assert.match(ui,/module\/\$\{state\.activeModuleId\}/);assert.match(ui,/aria-current="page"/);assert.match(ui,/allowedSections = currentUser/);assert.match(css,/\.user-app-link\.active[\s\S]*?var\(--nav-active-bg\)/);assert.match(css,/\.user-settings-subnav \.ui-button\.active[\s\S]*?var\(--nav-active-text\)/);assert.doesNotMatch(css,/user-settings-subnav[^}]*#[0-9a-f]{3,8}/i);});
